import { Asset } from 'expo-asset';

// All images bundled in the app — preloaded once at startup
const ALL_IMAGES = [
  require('../../assets/images/wappen/baden-wuerttemberg_wappen.png'),
  require('../../assets/images/wappen/bayern_wappen.png'),
  require('../../assets/images/wappen/berlin_wappen.png'),
  require('../../assets/images/wappen/brandenburg_wappen.png'),
  require('../../assets/images/wappen/bremen_wappen.png'),
  require('../../assets/images/wappen/hamburg_wappen.png'),
  require('../../assets/images/wappen/hessen_wappen.png'),
  require('../../assets/images/wappen/mecklenburg-vorpommern_wappen.png'),
  require('../../assets/images/wappen/niedersachsen_wappen.png'),
  require('../../assets/images/wappen/nordrhein-westfalen_wappen.png'),
  require('../../assets/images/wappen/rheinland-pfalz_wappen.png'),
  require('../../assets/images/wappen/saarland_wappen.png'),
  require('../../assets/images/wappen/sachsen_wappen.png'),
  require('../../assets/images/wappen/sachsen-anhalt_wappen.png'),
  require('../../assets/images/wappen/schleswig-holstein_wappen.png'),
  require('../../assets/images/wappen/thueringen_wappen.png'),
  require('../../assets/images/coats/q021.png'),
  require('../../assets/images/coats/q055.png'),
  require('../../assets/images/coats/q070.png'),
  require('../../assets/images/coats/q130.png'),
  require('../../assets/images/coats/q176.png'),
  require('../../assets/images/coats/q181.png'),
  require('../../assets/images/coats/q187.png'),
  require('../../assets/images/coats/q209.png'),
  require('../../assets/images/coats/q216.png'),
  require('../../assets/images/coats/q226.png'),
  require('../../assets/images/coats/q235.png'),
  require('../../assets/images/coats/baden_wuttemberg_001.png'),
  require('../../assets/images/coats/bayern_001.png'),
  require('../../assets/images/coats/berlin_001.png'),
  require('../../assets/images/coats/brandenburg_001.png'),
  require('../../assets/images/coats/bremen_001.png'),
  require('../../assets/images/coats/hamburg_001.png'),
  require('../../assets/images/coats/hessen_001.png'),
  require('../../assets/images/coats/mecklenburg_vorpommern_001.png'),
  require('../../assets/images/coats/niedersachsen_001.png'),
  require('../../assets/images/coats/nordrhein_westfalen_001.png'),
  require('../../assets/images/coats/rheinland_pfalz_001.png'),
  require('../../assets/images/coats/saarland_001.png'),
  require('../../assets/images/coats/sachsen_001.png'),
  require('../../assets/images/coats/sachsen_anhalt_001.png'),
  require('../../assets/images/coats/schleswig_holstein_001.png'),
  require('../../assets/images/coats/thueringen_001.png'),
  require('../../assets/images/coats/baden_wuttemberg_008.png'),
  require('../../assets/images/coats/bayern_008.png'),
  require('../../assets/images/coats/berlin_008.png'),
  require('../../assets/images/coats/brandenburg_008.png'),
  require('../../assets/images/coats/bremen_008.png'),
  require('../../assets/images/coats/hamburg_008.png'),
  require('../../assets/images/coats/hessen_008.png'),
  require('../../assets/images/coats/mecklenburg_vorpommern_008.png'),
  require('../../assets/images/coats/niedersachsen_008.png'),
  require('../../assets/images/coats/nordrhein_westfalen_008.png'),
  require('../../assets/images/coats/rheinland_pfalz_008.png'),
  require('../../assets/images/coats/saarland_008.png'),
  require('../../assets/images/coats/sachsen_008.png'),
  require('../../assets/images/coats/sachsen_anhalt_008.png'),
  require('../../assets/images/coats/schleswig_holstein_008.png'),
  require('../../assets/images/coats/thueringen_008.png'),
];

export async function preloadAssets(): Promise<void> {
  await Asset.loadAsync(ALL_IMAGES);
}
